version: '3.1'

services:

  db:
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_USER: flaskappdb
      POSTGRES_PASSWORD: flaskappdb
      POSTGRES_DB: flask_app
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data


volumes:
  pg_data:

