version: "0.2"

env:
  variables:
    SCRIPT: "bot.py"
    REGISTRY_ID: "163715734974"
    REPOSITORY_REGION: "eu-central-1"
    REPO_NAME: "${REGISTRY_ID}.dkr.ecr.${REPOSITORY_REGION}.amazonaws.com/auto_search_bot"
    TAG: "latest"

phases:
  build:
    commands:
      - cd "${CODEBUILD_SRC_DIR}/telegram_bot"
      - aws ecr get-login-password --region ${REPOSITORY_REGION} | docker login --username AWS --password-stdin ${REGISTRY_ID}.dkr.ecr.${REPOSITORY_REGION}.amazonaws.com
      - docker build -t ${REPO_NAME}:${TAG} --build-arg SCRIPT=${SCRIPT} -f ./Dockerfile .
      - docker push ${REPO_NAME}:${TAG}
